version: '2'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    labels:
      kompose.service.type: clusterip
    ports:
      - '5432:5432'

  webserver:
    # image: puckel/docker-airflow:1.10.4
    image: dshvimer/airflow-k8s
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - POSTGRES_PORT=5432

    volumes:
      - ./dags:/usr/local/airflow/dags
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow/plugins
    ports:
      - '8080:8080'
    command: webserver
    labels:
      kompose.service.type: nodeport
# kubectl run -i --tty --rm debug --image=postgres:9.6 --restart=Never -- bash
# docker build -t airflow/k8s .

